version: '3.8'

services:
 app:
  build: .
  image: owftecnologia/demo-cloud-devops:1.0
  restart: always
  container_name: demo-cloud-devops
  ports:
   - 8000:8000
  volumes:
   - .:/app
  command: uvicorn app:app --reload --host 0.0.0.0 --port 8000
